account_id_to_secret_phrase:                   # define accounts and passphrases for solo mining 
  10282355196851764065: 'glad suffer red during single glow shut slam hill death lust although'  
  1796535821016683299: 'stand rude those door invite reflection anywhere lace safe hidden fur horrible'  
plot_dirs:
  - 'test_data'
  - 'd:\plot' 
#  - 'C:\second\windows\plot\dir'
#  - '/first/linux/plot/dir'
#  - '/second/linux/plot/dir'

# url: 'http://pool.dev.burst-test.net:8124'   # testnet pool
url: 'http://wallet.dev.burst-test.net:6876'   # testnet wallet
# url: 'http://dummypool.megash.it'            # dummypool with constant scoop number for benchmarking

hdd_reader_thread_count: 0            # default 0 (=number of disks)
hdd_use_direct_io: true               # default true
hdd_wakeup_after: 240                 # default 240s

cpu_worker_thread_count: 4            # default 4 (0=GPU only)
cpu_nonces_per_cache: 65536           # default 65536
cpu_thread_pinning: false             # default false

gpu_platform: 0                       # default 0
gpu_device: 0                         # default 0
gpu_worker_thread_count: 0            # default 0 (=CPU only)
gpu_nonces_per_cache: 524288          # default 524288
gpu_mem_mapping: false                # default false

target_deadline: 4294967295           # default u32::MAX

get_mining_info_interval: 3000        # default 3000ms
timeout: 5000                         # default 5000ms

console_log_level: 'Info'             # default Info, Options (Off, Error, Warn, Info, Debug, Trace)
logfile_log_level: 'Warn'             # default Warn, Options (Off, Error, Warn, Info, Debug, Trace)
logfile_max_count: 10                 # maximum number of log files to keep
logfile_max_size : 20                 # maximum size per logfile in MiB

# Low noise log patterns
console_log_pattern: "\r{({d(%H:%M:%S)} [{l}]):16.16} {m}{n}"
logfile_log_pattern: "\r{({d(%Y-%m-%d %H:%M:%S)} [{l}]):26.26} {m}{n}"

# More detailed log patterns
#console_log_pattern: "\r{d(%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}] [{t}] - {M}:{m}{n}"
#logfile_log_pattern: "\r{d(%Y-%m-%dT%H:%M:%S.%3f%z)} [{h({l}):<5}] [{T}]-[{t}] [{f}:{L}] - {M}:{m}{n}"
