secret_phrase: 'glad suffer red during single glow shut slam hill death lust although'
account_id: 10282355196851764065
plot_dirs:
  - 'test_data'
#  - 'C:\first\windows\plot\dir'
#  - 'C:\second\windows\plot\dir'
#  - '/first/linux/plot/dir'
#  - '/second/linux/plot/dir'
# url: 'http://wallet.dev.burst-test.net:6876'
url: 'http://pool.dev.burst-test.net:8124'
worker_thread_count: 1
reader_thread_count: 1
nonces_per_cache: 65536               # default 65536
target_deadline: 10885484741537822773 # default u64::MAX
use_direct_io: true                   # default true
get_mining_info_interval: 3000        # default 3000ms
timeout: 5000                         # default 5000ms
wakeup_after: 240                     # default 240s
console_log_level: 'Info'             # default Info, Options (Off, Error, Warn Info)
logfile_log_level: 'Warn'             # default Warn, Options (Off, Error, Warn Info)
logfile_max_count: 10                 # maximum number of log files to keep
logfile_max_size : 20                 # maximum size per logfile in MiB
gpu_worker_thread_count: 1            # number of GPU workers (0 = CPU only)
gpu_platform: 0                       # select GPU platform
gpu_device: 0                         # select GPU device